spring:
  application:
    name: Store
  datasource:
      url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
      username: root
      password: zxc22331@NBnb!
      driver-class-name: com.mysql.cj.jdbc.Driver

stripe:
  apiURL: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD, INR, GBP
payment-gateway: Stripe